### ISSUE TITLE
Missing basic folders and files for the app

### ISSUE THREAD

**Issue by ChristoPy** [roqueando/konarium.io#1]
On running ```npm start``` the following folders and files are missing:

1. ```.\Notices``` that should have ```notices.json``` 

2. ```.\Konaries```

**Comment by roqueando** [comment]
That has been added and fixed. The file `notices.json` and those folders `./Notices` and `./Konaries` has been added.

**Comment by ChristoPy** [comment]
The files and folders are not there yet
