### ISSUE TITLE
No readable endpoints

### ISSUE THREAD

**Issue by ChristoPy** [roqueando/konarium.io#3]
The endpoints don't seems to be like an REST API, or be, the controller ```Store``` has the method ```Products```, so the request to see all products should be: ```www.mystore.com/store/products```.
The controllers are readable but your routes don't, or be:
```/meet``` should be: ```/user/meet```
```/publish```should be: ```/user/publish```
and so on...

This will help creating the app and using it more like an API, like it is designed to be.

**Comment by roqueando** [comment]
That is fixed, all routes are now RESTful endpoint style.
