### ISSUE TITLE
User created when the server starts

### ISSUE THREAD

**Issue by ChristoPy** [roqueando/konarium.io#4]
This is not an issue if the [Issue #3 ](https://github.com/roqueando/konarium.io/issues/3) be solved.

The dat informations (user) are created when the server runs, and it should be created calling the ```/user/create``` endpoint, and the files as mentioned here [Issue #1 ](https://github.com/roqueando/konarium.io/issues/1).

However, the user informations should be created when it be needed, loaded when needed, edited when needed... not when the server starts.

**Comment by roqueando** [comment]
The Dat information like the hash does not interfere on user information, then when the server starts only Dat information will be created just one time.
