### ISSUE TITLE
User information get removed if the key doesn't exist in the request

### ISSUE THREAD

**Issue by ChristoPy** [roqueando/konarium.io#5]
Let's assume that the user information is that:
```
{
	"me": {
		"avatar": "incredible giant base64 ",
		"name": "my cool name"
	},
	"id": "incredible giant sha"
}
```

When a key in the request  ```/user/edit``` is empty, that information on db is removed.
Or be, if I want to change the name, the query will be this:
```
name=my other cool name
```
But when we hit ```/```:
```
{
	"me": {
		"name": "my other cool name"
	},
	"id": "incredible giant sha"
}
```
The avatar info was removed.
I know, doesn't seems to be stupid if think that a ```PUT``` request is to put things. And put ```undefined``` will put an empty value.
But if be needed edit only one information, this will need to send the new info and the current.

**Comment by roqueando** [comment]
I know, but that is the old config, I will adjust that because the front end is completely different.

**Comment by roqueando** [comment]
Now, fixed!
